import { collectExtraColorVars } from "./mergeTheme";
import { generateThemeUtilities } from "./generateUtilities";
import type { ResolvedThemeConfig, ThemeColorMap, ThemeName } from "./types";

/**
 * @param {ThemeColorMap} colors
 */
function formatColorBlock(colors: ThemeColorMap): string {
    return Object.entries(colors)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([cssVar, value]) => `    ${cssVar}: ${value};`)
        .join("\n");
}

/**
 * @param {string[]} extraVars
 */
function generateExtraThemeRegistration(extraVars: string[]): string {
    if (extraVars.length === 0) {
        return "";
    }

    const lines = extraVars.map((cssVar) => `    ${cssVar}: var(${cssVar});`).join("\n");

    return `@theme inline {\n${lines}\n}\n\n`;
}

/**
 * @param {ResolvedThemeConfig} config
 */
export function generateClientThemeCss(config: ResolvedThemeConfig): string {
    const extraVars = collectExtraColorVars(config.themes);
    const utilities = generateThemeUtilities(config.radius);

    const darkBlock = formatColorBlock(config.themes.dark);
    const lightBlock = formatColorBlock(config.themes.light);

    return `/* Generated by clientTheme vite plugin — do not edit manually */
${generateExtraThemeRegistration(extraVars)}:root,
[data-theme="dark"] {
${darkBlock}
}

[data-theme="light"] {
${lightBlock}
}

${utilities}
`;
}

/**
 * @param {ThemeName} themeName
 */
export function themeSelector(themeName: ThemeName): string {
    return themeName === "dark" ? ':root, [data-theme="dark"]' : '[data-theme="light"]';
}
