import { generateThemeUtilities } from "./generateUtilities";
import type { ResolvedThemeConfig, ThemeColorMap, ThemeName } from "./types";

/**
 * Formats the theme color block to CSS
 * @example
 * ```css
 * background: oklch(0.145 0 0);
 * foreground: oklch(0.95 0 0);
 * shadow: rgba(0, 0, 0, 0.25);
 * card: oklch(0.205 0 0);
 * "card-foreground": oklch(0.985 0 0);
 * ```
 * @param {ThemeColorMap} colors
 */
function formatColorBlock(colors: ThemeColorMap): string {
    return Object.entries(colors)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([cssVar, value]) => `    ${cssVar}: ${value};`)
        .join("\n");
}

/**
 * Registers Tailwind color tokens as aliases so `[data-theme]` can change the
 * actual `--color-*` values. A static `@theme { --color-accent: … }` block
 * would re-emit dark values on `:root` and override light theme.
 *
 * @param {Record<ThemeName, ThemeColorMap>} themes
 */
function generateThemeTokenRegistration(themes: Record<ThemeName, ThemeColorMap>): string {
    const vars = new Set<string>();

    for (const colors of Object.values(themes)) {
        for (const cssVar of Object.keys(colors)) {
            vars.add(cssVar);
        }
    }

    const lines = [...vars]
        .sort()
        .map((cssVar) => `    ${cssVar}: var(${cssVar});`)
        .join("\n");

    return `@theme inline {\n${lines}\n}\n\n`;
}

/**
 * Generates the CSS for the client theme
 * @example
 * ```css
 * :root, [data-theme="dark"] {
 *   background: oklch(0.145 0 0);
 *   foreground: oklch(0.95 0 0);
 *   shadow: rgba(0, 0, 0, 0.25);
 * }
 * ```
 * @param {ResolvedThemeConfig} config
 */
export function generateClientThemeCss(config: ResolvedThemeConfig): string {
    const utilities = generateThemeUtilities(config.radius);

    const darkBlock = formatColorBlock(config.themes.dark);
    const lightBlock = formatColorBlock(config.themes.light);

    return `/* Generated by clientTheme vite plugin — do not edit manually */
${generateThemeTokenRegistration(config.themes)}:root,
[data-theme="dark"] {
${darkBlock}
}

[data-theme="light"] {
${lightBlock}
}

${utilities}
`;
}

/**
 * Generates the selector for the theme
 * @example
 * ```css
 * :root, [data-theme="dark"]
 * ```
 * @param {ThemeName} themeName
 */
export function themeSelector(themeName: ThemeName): string {
    return themeName === "dark" ? ':root, [data-theme="dark"]' : '[data-theme="light"]';
}
